external_components:
  - source: github://maciekczwa/esphome_somfy

esphome:
  name: somfy

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret ssid_dol
  password: !secret wifi_password

logger:
  level: DEBUG

api:
  password: !secret api_password

ota:
  platform: esphome
  password: !secret ota_password

remote_transmitter:
  id: transmitter
  pin: 4
  carrier_duty_percent: 100%

somfy:
  address: 0x1A7A11


